// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID        string `json:"_id"`
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
}

type Book struct {
	ID     string  `json:"_id"`
	Title  string  `json:"title"`
	Author *Author `json:"author"`
}

type NewAuthor struct {
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
}

type NewBook struct {
	Title  string  `json:"title"`
	Author *Author `json:"author"`
}
